# Generated by Django 5.2.4 on 2025-12-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionApp', '0003_questiongroup_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
