# Generated by Django 5.2.4 on 2025-12-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionApp', '0004_questiongroup_time'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionApp.questiongroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.profile')),
            ],
        ),
    ]
